name: Sonar CI - Kalunga

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-and-scan:
    runs-on: macos-latest
    steps:
      - name: Checkout Files
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
        
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Generate Coverage Report
        run: ./gradlew jacocoTestReport

      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: "app/build/reports/jacoco/jacocoTestReport/html/"

      - name: Sonarscan
        run: ./gradlew sonarqube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.TOKEN_CI }}
